import type { NextConfig } from "next";
import legacyRedirects from "./docs/redirects/redirects.json";

/**
 * Legacy WooCommerce -> storefront redirects (CLNT-175).
 *
 * `docs/redirects/redirects.json` is generated by
 * `scripts/redirects/build_redirect_map.py` and holds only the Next.js-owned
 * permanent rows of `docs/redirects/redirect-map.csv`. `permanent: true` emits a
 * 308. Never edit the JSON by hand; rerun the builder.
 */
type Redirect = { source: string; destination: string; permanent: boolean };

const nextConfig: NextConfig = {
  // Trailing-slash normalisation is done in src/proxy.ts so a legacy WordPress
  // URL ("/product/x/") reaches its mapped destination or a 410 in one hop.
  skipTrailingSlashRedirect: true,
  images: {
    // Shopify serves every product image from its CDN; nothing else is allowed.
    remotePatterns: [
      {
        protocol: "https",
        hostname: "cdn.shopify.com",
        port: "",
        pathname: "/s/files/**",
      },
    ],
  },
  async redirects(): Promise<Redirect[]> {
    return legacyRedirects satisfies Redirect[];
  },
};

export default nextConfig;
