import type { NextConfig } from "next";
import legacyRedirects from "./docs/redirects/redirects.json";
import { securityHeaders } from "./src/lib/security-headers.ts";

/**
 * Legacy WooCommerce -> storefront redirects (CLNT-175).
 *
 * `docs/redirects/redirects.json` is generated by
 * `scripts/redirects/build_redirect_map.py` and holds only the Next.js-owned
 * permanent rows of `docs/redirects/redirect-map.csv`. `permanent: true` emits a
 * 308. Never edit the JSON by hand; rerun the builder.
 */
type Redirect = { source: string; destination: string; permanent: boolean };

const nextConfig: NextConfig = {
  // Trailing-slash normalisation is done in src/proxy.ts so a legacy WordPress
  // URL ("/product/x/") reaches its mapped destination or a 410 in one hop.
  skipTrailingSlashRedirect: true,
  images: {
    // Shopify serves every product image from its CDN; nothing else is allowed.
    remotePatterns: [
      {
        protocol: "https",
        hostname: "cdn.shopify.com",
        port: "",
        pathname: "/s/files/**",
      },
    ],
  },
  async redirects(): Promise<Redirect[]> {
    return legacyRedirects satisfies Redirect[];
  },
  /**
   * Security headers on every response (CLNT-179, defects D5 and D6). The list
   * and the reasoning behind each CSP directive live in
   * `src/lib/security-headers.ts`; the policy is documented in
   * `docs/deployment.md` § Security headers.
   *
   * `/:path*` matches every route including `/`. HSTS is not set here — the
   * host (Vercel) already sends `max-age=63072000; includeSubDomains; preload`.
   */
  async headers() {
    return [
      {
        source: "/:path*",
        headers: securityHeaders(process.env.NODE_ENV === "development"),
      },
    ];
  },
};

export default nextConfig;
