#!/usr/bin/env node
/**
 * CLNT-179 / Workstream 7 — security and SEO evidence.
 *
 * Covers docs/prosporter-project-schedule.md section 1 criteria 5 (HTTPS
 * enforced, no secrets in client-side code) and 6 (unique title and meta
 * description per page, semantic headings, sitemap.xml, robots.txt, Open
 * Graph), plus the transport headers and cookie flags a modern store is
 * expected to carry.
 *
 * Checks:
 *   1. `http://` -> `https://` redirect, HSTS, X-Content-Type-Options,
 *      Referrer-Policy, X-Frame-Options, CSP, Permissions-Policy.
 *   2. `/robots.txt` and `/sitemap.xml` content.
 *   3. Per-page `<title>`, meta description, canonical, `og:title`,
 *      `og:description`, `og:image`, robots meta — and whether each is unique
 *      across the sample.
 *   4. JSON-LD presence and JSON validity on a product page and an article.
 *   5. Every first-party `/_next/static/**.js` chunk referenced by the sampled
 *      pages is downloaded and grepped for secret shapes (`shpat_`, `shpss_`,
 *      `shpca_`, Storefront access tokens, `RESEND_`, `re_` API keys, private
 *      keys, and any live value of SHOPIFY_STOREFRONT_TOKEN taken from the
 *      environment if present). Matches are reported as a shape and a location
 *      only — never as the secret itself.
 *   6. The `prosporter_cart` cookie's flags, read out of a real browser session
 *      after adding an item to the cart through the UI.
 *   7. A POST to /api/webhooks/shopify carrying an invalid HMAC signature,
 *      which must be rejected.
 *
 * Usage: node scripts/qa/security-and-seo.mjs [--base URL] [--port 9344]
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { Cdp, closeTab, launchChrome, newTab, sleep } from "./cdp.mjs";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const QA = path.join(REPO, "docs", "qa");

const argv = process.argv.slice(2);
const flag = (n, d) => { const i = argv.indexOf(`--${n}`); return i === -1 ? d : argv[i + 1]; };
const BASE = String(flag("base", "https://prosporter.vercel.app")).replace(/\/$/, "");
const PORT = Number(flag("port", 9344));
const UA = "ProSporter-QA/1.0 (+CLNT-179 acceptance evidence; read-only)";

const PAGE_PATHS = [
  ["home", "/"],
  ["shop", "/shop"],
  ["collection", "/shop/jerseys"],
  ["product", "/product/ace-unisex"],
  ["search", "/search?q=jersey"],
  ["blog", "/blog"],
  ["article", null],
  ["contact", "/contact"],
  ["not-found", "/qa-404-check-clnt-179"],
];

const get = (url, init = {}) =>
  fetch(url, { redirect: "manual", headers: { "user-agent": UA, ...(init.headers ?? {}) }, ...init });

const meta = (html, name) =>
  new RegExp(`<meta[^>]+(?:name|property)=["']${name}["'][^>]*>`, "i").exec(html)?.[0] ?? "";
const content = (tag) => /content=["']([^"']*)["']/i.exec(tag)?.[1] ?? "";
const yn = (v) => (v ? "yes" : "**no**");

async function main() {
  await mkdir(QA, { recursive: true });
  const md = [];
  const defects = [];

  md.push("# Security and SEO (CLNT-179, Workstream 7)");
  md.push("");
  md.push(`- Target: \`${BASE}\``);
  md.push(`- Generated by \`scripts/qa/security-and-seo.mjs\` on ${new Date().toISOString()}. Read-only; no secret value is ever written to this file.`);
  md.push("");
  md.push("Acceptance criteria covered: section 1 criterion 5 (HTTPS enforced site-wide, no credentials or secrets in client-side code) and criterion 6 (unique title and meta description per page, semantic heading structure, sitemap.xml, robots.txt, Open Graph).");
  md.push("");

  // ---- 1. transport ------------------------------------------------------
  const host = new URL(BASE).host;
  const httpRes = await get(`http://${host}/`).catch((e) => ({ error: String(e) }));
  const httpsRes = await get(`${BASE}/`);
  const h = (n) => httpsRes.headers.get(n);

  md.push("## Transport security");
  md.push("");
  md.push("| Check | Result | Verdict |");
  md.push("|---|---|---|");
  const httpStatus = httpRes.status ?? 0;
  const httpLoc = httpRes.headers?.get?.("location") ?? "";
  const httpOk = httpStatus >= 300 && httpStatus < 400 && httpLoc.startsWith("https://");
  md.push(`| \`http://${host}/\` | ${httpStatus} -> \`${httpLoc || "(none)"}\` | ${httpOk ? "PASS" : "FAIL"} |`);
  if (!httpOk) defects.push({ sev: "high", what: `Plain http:// is not redirected to https:// (got ${httpStatus})`, url: `http://${host}/` });

  const hsts = h("strict-transport-security") ?? "";
  const hstsMax = Number(/max-age=(\d+)/i.exec(hsts)?.[1] ?? 0);
  const hstsOk = hstsMax >= 15552000;
  md.push(`| \`Strict-Transport-Security\` | \`${hsts || "(absent)"}\` | ${hstsOk ? "PASS" : "FAIL"} |`);
  if (!hstsOk) defects.push({ sev: "high", what: `HSTS missing or max-age below 180 days (${hsts || "absent"})`, url: `${BASE}/` });

  const checks = [
    ["X-Content-Type-Options", "x-content-type-options", (v) => v?.toLowerCase() === "nosniff", "medium"],
    ["Referrer-Policy", "referrer-policy", (v) => Boolean(v), "medium"],
    ["X-Frame-Options / frame-ancestors", "x-frame-options", (v) => Boolean(v) || Boolean(h("content-security-policy")?.includes("frame-ancestors")), "medium"],
    ["Content-Security-Policy", "content-security-policy", (v) => Boolean(v), "low"],
    ["Permissions-Policy", "permissions-policy", (v) => Boolean(v), "low"],
    ["X-Robots-Tag", "x-robots-tag", () => true, "info"],
  ];
  for (const [label, name, ok, sev] of checks) {
    const v = h(name);
    const pass = ok(v);
    md.push(`| \`${label}\` | \`${v ?? "(absent)"}\` | ${pass ? "PASS" : "MISSING"} |`);
    if (!pass && sev !== "info") defects.push({ sev, what: `${label} header absent or wrong on HTML responses`, url: `${BASE}/` });
  }
  md.push("");
  md.push("> `x-robots-tag: noindex, nofollow` is expected on this deployment: `NEXT_PUBLIC_SITE_URL` is unset, so `isIndexableDeployment()` is false (commit 70dc500) and the storefront stays out of the index until cutover. Not a defect.");
  md.push("");

  // ---- 2. robots and sitemap --------------------------------------------
  const robotsTxt = await (await get(`${BASE}/robots.txt`)).text();
  const sitemapXml = await (await get(`${BASE}/sitemap.xml`)).text();
  const locs = [...sitemapXml.matchAll(/<loc>\s*([^<\s]+)\s*<\/loc>/gi)].map((m) => m[1]);

  md.push("## robots.txt and sitemap.xml");
  md.push("");
  md.push("`/robots.txt`:");
  md.push("");
  md.push("```");
  md.push(robotsTxt.trim());
  md.push("```");
  md.push("");
  md.push(`\`/sitemap.xml\`: ${locs.length} \`<loc>\` entr${locs.length === 1 ? "y" : "ies"}${locs.length ? ` — first: \`${locs[0]}\`` : ""}.`);
  md.push("");
  if (/^\s*disallow:\s*\/\s*$/im.test(robotsTxt) || locs.length <= 1) {
    md.push("Both files are in their pre-cutover shape. `src/app/robots.ts` returns disallow-all and `src/app/sitemap.ts` returns the home URL only whenever `isIndexableDeployment()` is false. The production shapes (allow-all with a sitemap reference, and roughly 200 URLs) cannot be observed until `NEXT_PUBLIC_SITE_URL` is set at cutover, so **criterion 6's sitemap/robots half is not yet testable on this deployment**. The code paths are reviewable in `src/app/robots.ts` and `src/app/sitemap.ts`.");
    md.push("");
  }

  // ---- 3. per-page SEO ---------------------------------------------------
  const blogHtml = await (await get(`${BASE}/blog`)).text();
  const articleHref = [...blogHtml.matchAll(/href="(\/blog\/[^"#?]+)"/g)].map((m) => m[1]).find((x) => x !== "/blog");
  const pages = PAGE_PATHS.map(([l, p]) => [l, l === "article" ? (articleHref ?? "/blog") : p]);

  const seo = [];
  for (const [label, p] of pages) {
    const res = await get(`${BASE}${p}`, { redirect: "follow" });
    const html = await res.text();
    seo.push({
      label, path: p, status: res.status,
      title: (/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1] ?? "").trim(),
      description: content(meta(html, "description")),
      canonical: /<link[^>]+rel=["']canonical["'][^>]*>/i.exec(html)?.[0]?.match(/href=["']([^"']*)["']/i)?.[1] ?? "",
      ogTitle: content(meta(html, "og:title")),
      ogDescription: content(meta(html, "og:description")),
      ogImage: content(meta(html, "og:image")),
      ogType: content(meta(html, "og:type")),
      twitterCard: content(meta(html, "twitter:card")),
      robotsMeta: content(meta(html, "robots")),
      h1Count: (html.match(/<h1[\s>]/gi) ?? []).length,
      jsonLd: [...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].map((m) => m[1]),
      scripts: [...html.matchAll(/src="(\/_next\/static\/[^"]+\.js)"/g)].map((m) => m[1]),
      html,
    });
    await sleep(120);
  }

  const dupe = (key) => {
    const m = new Map();
    for (const s of seo) {
      if (!s[key]) continue;
      m.set(s[key], [...(m.get(s[key]) ?? []), s.label]);
    }
    return [...m.entries()].filter(([, v]) => v.length > 1);
  };

  md.push("## Per-page SEO metadata");
  md.push("");
  md.push("| Page | Status | `<title>` | Meta description | Canonical | `og:title` | `og:image` | h1 |");
  md.push("|---|---:|---|---|---|---|---|---:|");
  for (const s of seo) {
    md.push(`| ${s.label} \`${s.path}\` | ${s.status} | ${s.title ? `\`${s.title.slice(0, 70)}\`` : "**missing**"} | ${s.description ? `${s.description.length} chars` : "**missing**"} | ${yn(s.canonical)} | ${yn(s.ogTitle)} | ${yn(s.ogImage)} | ${s.h1Count} |`);
  }
  md.push("");
  const dupTitles = dupe("title");
  const dupDescs = dupe("description");
  md.push(`- Duplicate \`<title>\` values: ${dupTitles.length ? dupTitles.map(([v, ls]) => `\`${v.slice(0, 60)}\` on ${ls.join(", ")}`).join("; ") : "none"}.`);
  md.push(`- Duplicate meta descriptions: ${dupDescs.length ? dupDescs.map(([, ls]) => ls.join(", ")).join("; ") : "none"}.`);
  const missingTitle = seo.filter((s) => !s.title).map((s) => s.label);
  const missingDesc = seo.filter((s) => !s.description).map((s) => s.label);
  const missingCanon = seo.filter((s) => !s.canonical).map((s) => s.label);
  const missingOg = seo.filter((s) => !s.ogTitle).map((s) => s.label);
  md.push(`- Missing \`<title>\`: ${missingTitle.length ? missingTitle.join(", ") : "none"}.`);
  md.push(`- Missing meta description: ${missingDesc.length ? missingDesc.join(", ") : "none"}.`);
  md.push(`- Missing canonical: ${missingCanon.length ? missingCanon.join(", ") : "none"}.`);
  md.push(`- Missing \`og:title\`: ${missingOg.length ? missingOg.join(", ") : "none"}.`);
  md.push(`- Pages with a heading count other than exactly one \`<h1>\`: ${seo.filter((s) => s.h1Count !== 1).map((s) => `${s.label} (${s.h1Count})`).join(", ") || "none"}.`);
  md.push("");
  if (dupTitles.length) defects.push({ sev: "medium", what: `Duplicate <title> across pages: ${dupTitles.map(([, l]) => l.join("/")).join("; ")}`, url: BASE });
  if (missingDesc.length) defects.push({ sev: "medium", what: `Meta description missing on: ${missingDesc.join(", ")}`, url: BASE });
  if (missingCanon.length) defects.push({ sev: "low", what: `Canonical link missing on: ${missingCanon.join(", ")}`, url: BASE });
  if (missingOg.length) defects.push({ sev: "medium", what: `og:title missing on: ${missingOg.join(", ")}`, url: BASE });

  md.push("### Full metadata values");
  md.push("");
  for (const s of seo) {
    md.push(`**${s.label}** \`${s.path}\` (${s.status})`);
    md.push("");
    md.push(`- title: \`${s.title || "(none)"}\``);
    md.push(`- description: \`${s.description || "(none)"}\``);
    md.push(`- canonical: \`${s.canonical || "(none)"}\``);
    md.push(`- og:title / og:description / og:image / og:type: \`${s.ogTitle || "-"}\` / \`${(s.ogDescription || "-").slice(0, 90)}\` / \`${s.ogImage || "-"}\` / \`${s.ogType || "-"}\``);
    md.push(`- twitter:card: \`${s.twitterCard || "(none)"}\`; robots meta: \`${s.robotsMeta || "(none)"}\``);
    md.push("");
  }

  // ---- 4. JSON-LD --------------------------------------------------------
  md.push("## Structured data (JSON-LD)");
  md.push("");
  md.push("| Page | Blocks | Valid JSON | `@type` values |");
  md.push("|---|---:|---|---|");
  for (const s of seo) {
    if (!["product", "article", "home", "collection", "blog"].includes(s.label)) continue;
    const types = [];
    let valid = true;
    for (const block of s.jsonLd) {
      try {
        const parsed = JSON.parse(block);
        const walk = (n) => {
          if (Array.isArray(n)) return n.forEach(walk);
          if (n && typeof n === "object") {
            if (n["@type"]) types.push(String(n["@type"]));
            Object.values(n).forEach(walk);
          }
        };
        walk(parsed);
      } catch { valid = false; }
    }
    md.push(`| ${s.label} | ${s.jsonLd.length} | ${s.jsonLd.length === 0 ? "n/a" : valid ? "PASS" : "**FAIL**"} | ${[...new Set(types)].join(", ") || "—"} |`);
    if (s.jsonLd.length === 0 && (s.label === "product" || s.label === "article")) {
      defects.push({ sev: "medium", what: `No JSON-LD structured data on the ${s.label} page`, url: `${BASE}${s.path}` });
    }
    if (!valid) defects.push({ sev: "medium", what: `Invalid JSON in a JSON-LD block on the ${s.label} page`, url: `${BASE}${s.path}` });
  }
  md.push("");

  // ---- 5. secrets in client bundles --------------------------------------
  const chunks = [...new Set(seo.flatMap((s) => s.scripts))];
  const PATTERNS = [
    ["Shopify Admin API access token", /shpat_[0-9a-f]{16,}/gi],
    ["Shopify shared secret", /shpss_[0-9a-f]{16,}/gi],
    ["Shopify custom app token", /shpca_[0-9a-f]{16,}/gi],
    ["Named env var SHOPIFY_STOREFRONT_TOKEN", /SHOPIFY_STOREFRONT_TOKEN/g],
    ["Named env var SHOPIFY_ADMIN_CLIENT_SECRET", /SHOPIFY_ADMIN_CLIENT_SECRET/g],
    ["Named env var SHOPIFY_WEBHOOK_SECRET", /SHOPIFY_WEBHOOK_SECRET/g],
    ["Resend env var prefix", /RESEND_[A-Z_]+/g],
    ["Resend API key", /\bre_[A-Za-z0-9_-]{20,}/g],
    ["Private key block", /-----BEGIN [A-Z ]*PRIVATE KEY-----/g],
    ["32-hex Storefront-token shape", /["'][0-9a-f]{32}["']/g],
  ];
  // If the operator has the real token in their environment, look for its
  // literal value too. Never printed.
  const liveToken = process.env.SHOPIFY_STOREFRONT_TOKEN ?? process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN ?? "";

  const findings = [];
  let scanned = 0, bytes = 0;
  for (const c of chunks) {
    const r = await get(`${BASE}${c}`, { redirect: "follow" });
    if (!r.ok) continue;
    const body = await r.text();
    scanned += 1; bytes += body.length;
    for (const [label, re] of PATTERNS) {
      const hits = body.match(re);
      if (hits) findings.push({ chunk: c, label, count: hits.length });
    }
    if (liveToken && body.includes(liveToken)) findings.push({ chunk: c, label: "LIVE Storefront token value", count: 1 });
  }

  md.push("## Secrets in client-side code");
  md.push("");
  md.push(`Scanned **${scanned}** first-party \`/_next/static/**.js\` chunks referenced by the sampled pages (${Math.round(bytes / 1024)} KB of JavaScript as served) for credential shapes. Only the shape and the chunk are reported; no matched value is ever written here.`);
  md.push("");
  if (!findings.length) {
    md.push("**No match for any of:** `shpat_`, `shpss_`, `shpca_`, `SHOPIFY_STOREFRONT_TOKEN`, `SHOPIFY_ADMIN_CLIENT_SECRET`, `SHOPIFY_WEBHOOK_SECRET`, `RESEND_*`, `re_<key>`, a PEM private key block, or a bare 32-hex string literal.");
    md.push("");
    md.push(liveToken
      ? "The live Storefront token from the local environment was additionally searched for byte-for-byte and does not appear in any served chunk."
      : "No Storefront token was present in this machine's environment, so the byte-for-byte value search was skipped; the shape searches above still apply.");
  } else {
    md.push("| Chunk | Shape matched | Occurrences |");
    md.push("|---|---|---:|");
    for (const f of findings) md.push(`| \`${f.chunk}\` | ${f.label} | ${f.count} |`);
    for (const f of findings) {
      const critical = /LIVE|shpat_|shpss_|shpca_|Private key|re_/.test(f.label);
      defects.push({ sev: critical ? "critical" : "medium", what: `Possible secret shape in a client bundle: ${f.label} in ${f.chunk}`, url: `${BASE}${f.chunk}` });
    }
  }
  md.push("");

  // ---- 6. cart cookie ----------------------------------------------------
  md.push("## `prosporter_cart` cookie");
  md.push("");
  let cookieRow = null;
  let cookieNote = "";
  let cartAdded = false;
  const { proc, version } = await launchChrome(PORT);
  try {
    const { cdp, targetId } = await newTab(PORT);
    await cdp.send("Page.enable");
    await cdp.send("Network.enable");
    await cdp.send("Runtime.enable");
    const productUrl = `${BASE}/product/ace-unisex`;
    const loaded = new Promise((r) => cdp.on("Page.loadEventFired", r));
    await cdp.send("Page.navigate", { url: productUrl });
    await Promise.race([loaded, sleep(30000)]);
    await sleep(2500);

    // A variant must be chosen first: the product page renders one radio
    // fieldset per option and refuses the add with "Please choose size and
    // colour" until every group has a selection.
    const selected = await cdp.evaluate(`(() => {
      const picked = [];
      for (const fs of document.querySelectorAll('fieldset')) {
        const radios = [...fs.querySelectorAll('input[type=radio]')].filter(r => !r.disabled);
        if (!radios.length) continue;
        const r = radios.find(x => x.checked) ?? radios[0];
        r.click();
        const legend = (fs.querySelector('legend')?.innerText ?? '').trim().slice(0, 20);
        picked.push(legend + '=' + (r.value || r.getAttribute('aria-label') || ''));
      }
      return picked;
    })()`);
    await sleep(1200);

    const clicked = await cdp.evaluate(`(() => {
      const cands = [...document.querySelectorAll('button, [role=button], input[type=submit]')];
      const btn = cands.find(b => /add to (cart|bag)/i.test((b.innerText || b.value || '') + ' ' + (b.getAttribute('aria-label') || '')) && !b.disabled);
      if (!btn) return { ok: false, seen: cands.map(b => (b.innerText||b.value||'').trim().slice(0,40)).filter(Boolean).slice(0,12) };
      btn.click();
      return { ok: true, label: (btn.innerText||btn.value||'').trim().slice(0,40) };
    })()`);
    if (clicked?.ok) {
      // The cookie lands on the server-action response, but the bag control
      // only re-renders once React has the new cart. Poll the *UI* — the
      // cookie appearing first would otherwise read as a failed add.
      const readBag = () => cdp.evaluate(`(() => ({
        label: [...document.querySelectorAll('[aria-label]')].map(e => e.getAttribute('aria-label')).find(t => /bag,|cart,/i.test(t)) ?? null,
        alerts: [...document.querySelectorAll('[role=alert],[role=status]')].map(e => e.innerText.trim().slice(0, 140)).filter(Boolean).slice(0, 4),
      }))()`);
      let bag = await readBag();
      for (let i = 0; i < 15 && !/[1-9]\d* item/i.test(bag?.label ?? ""); i += 1) {
        await sleep(1500);
        bag = await readBag();
      }
      const { cookies } = await cdp.send("Network.getCookies", {});
      cookieRow = cookies.find((c) => c.name === "prosporter_cart") ?? null;
      cookieNote = `Selected a variant (${(selected ?? []).join(", ") || "no option groups"}), clicked "${clicked.label}". Bag control afterwards: \`${bag?.label ?? "unknown"}\`.${(bag?.alerts ?? []).length ? ` Live-region messages: ${bag.alerts.map((a) => `\`${a}\``).join("; ")}.` : ""}`;
      cartAdded = /[1-9]\d* item/i.test(bag?.label ?? "");
      if (!cartAdded) defects.push({ sev: "critical", what: `Add to cart did not increment the bag after selecting a variant (bag reads "${bag?.label ?? "unknown"}")`, url: productUrl });
    } else {
      cookieNote = `Could not find an enabled add-to-cart control on ${productUrl}. Buttons seen: ${(clicked?.seen ?? []).map((s) => `\`${s}\``).join(", ") || "none"}.`;
    }
    cdp.close();
    await closeTab(PORT, targetId);
  } catch (err) {
    cookieNote = `Browser step failed: ${err.message}`;
  } finally {
    proc.kill("SIGTERM");
  }

  md.push(`Driven with ${version?.Browser ?? "headless Chrome"} over the DevTools Protocol. ${cookieNote}`);
  md.push("");
  md.push(`Add-to-cart outcome: **${cartAdded ? "item added" : "no item added"}**. This doubles as live evidence for schedule section 3 criterion 3's first step; discount codes, shipping, payment and order confirmation still need a real test order through Shopify checkout.`);
  md.push("");
  if (cookieRow) {
    md.push("| Attribute | Value | Expected | Verdict |");
    md.push("|---|---|---|---|");
    md.push(`| \`HttpOnly\` | ${cookieRow.httpOnly} | true | ${cookieRow.httpOnly ? "PASS" : "**FAIL**"} |`);
    md.push(`| \`Secure\` | ${cookieRow.secure} | true | ${cookieRow.secure ? "PASS" : "**FAIL**"} |`);
    md.push(`| \`SameSite\` | ${cookieRow.sameSite ?? "(unset)"} | Lax or Strict | ${/lax|strict/i.test(cookieRow.sameSite ?? "") ? "PASS" : "**FAIL**"} |`);
    md.push(`| \`Path\` | ${cookieRow.path} | / | ${cookieRow.path === "/" ? "PASS" : "check"} |`);
    md.push(`| \`Domain\` | ${cookieRow.domain} | the storefront host | info |`);
    md.push(`| Session / expiry | ${cookieRow.session ? "session cookie" : new Date(cookieRow.expires * 1000).toISOString()} | — | info |`);
    md.push(`| Value | *(a Shopify cart GID — not recorded here)* | — | — |`);
    md.push("");
    if (!cookieRow.httpOnly) defects.push({ sev: "high", what: "prosporter_cart cookie is not HttpOnly", url: BASE });
    if (!cookieRow.secure) defects.push({ sev: "high", what: "prosporter_cart cookie is not Secure", url: BASE });
    if (!/lax|strict/i.test(cookieRow.sameSite ?? "")) defects.push({ sev: "medium", what: `prosporter_cart cookie SameSite is ${cookieRow.sameSite ?? "unset"}`, url: BASE });
  } else {
    md.push("No `prosporter_cart` cookie was observed. `src/lib/shopify/cart-actions.ts` sets it with `httpOnly: true`, `sameSite: \"lax\"` and `secure: process.env.NODE_ENV === \"production\"`; that is a code reading, not a live observation, so this row is **evidence pending**.");
    md.push("");
  }

  // ---- 7. webhook signature ---------------------------------------------
  const badBody = JSON.stringify({ id: 1, qa: "CLNT-179 invalid-signature probe" });
  const hookRes = await get(`${BASE}/api/webhooks/shopify`, {
    method: "POST",
    body: badBody,
    headers: {
      "content-type": "application/json",
      "x-shopify-hmac-sha256": "aW52YWxpZC1zaWduYXR1cmUtZm9yLXFhLXByb2Jl",
      "x-shopify-topic": "products/update",
      "x-shopify-shop-domain": "ihuvab-u2.myshopify.com",
      "x-shopify-webhook-id": "clnt-179-qa-probe",
    },
  });
  const hookText = (await hookRes.text()).slice(0, 200);
  const hookRejected = hookRes.status === 401 || hookRes.status === 403 || hookRes.status === 400 || hookRes.status === 500;
  md.push("## Webhook signature rejection");
  md.push("");
  md.push(`POST \`/api/webhooks/shopify\` with a deliberately invalid \`X-Shopify-Hmac-Sha256\`:`);
  md.push("");
  md.push(`- Response: **${hookRes.status} ${hookRes.statusText}** — \`${hookText.replace(/`/g, "'")}\``);
  md.push(`- Verdict: ${hookRes.status === 200 ? "**FAIL — an unsigned request was accepted**" : "PASS — not accepted"}.`);
  md.push("");
  md.push("`docs/webhooks.md`: the receiver answers **500** when `SHOPIFY_WEBHOOK_SECRET` is unset (so Shopify retries rather than the event being silently dropped) and **401** when the secret is set and the HMAC does not verify. Either way an unsigned request never revalidates a cache tag. A 500 here means the secret is not configured on this deployment yet.");
  md.push("");
  if (hookRes.status === 200) defects.push({ sev: "critical", what: "Webhook receiver accepted a request with an invalid HMAC signature", url: `${BASE}/api/webhooks/shopify` });
  else if (hookRes.status === 500) defects.push({ sev: "low", what: "SHOPIFY_WEBHOOK_SECRET is not configured on this deployment (receiver returns 500, correctly refusing the event)", url: `${BASE}/api/webhooks/shopify` });

  // ---- defects -----------------------------------------------------------
  md.push("## Defects found in this file");
  md.push("");
  if (!defects.length) md.push("None.");
  else {
    md.push("| Severity | Defect | URL |");
    md.push("|---|---|---|");
    for (const d of defects) md.push(`| ${d.sev} | ${d.what} | \`${d.url}\` |`);
  }
  md.push("");

  await writeFile(path.join(QA, "security-and-seo.md"), `${md.join("\n")}\n`);
  await writeFile(path.join(QA, "security-and-seo.json"), `${JSON.stringify({
    base: BASE, generated: new Date().toISOString(),
    headers: Object.fromEntries([...httpsRes.headers.entries()].filter(([k]) => !/^set-cookie$/i.test(k))),
    httpRedirect: { status: httpStatus, location: httpLoc },
    seo: seo.map(({ html, scripts, jsonLd, ...rest }) => ({ ...rest, jsonLdBlocks: jsonLd.length, chunkCount: scripts.length })),
    chunksScanned: scanned, secretFindings: findings,
    cartAdded,
    cartCookie: cookieRow ? { httpOnly: cookieRow.httpOnly, secure: cookieRow.secure, sameSite: cookieRow.sameSite, path: cookieRow.path, session: cookieRow.session } : null,
    webhook: { status: hookRes.status, rejected: hookRejected },
    defects,
  }, null, 2)}\n`);
  console.error("[sec] wrote docs/qa/security-and-seo.md");
}

main().catch((e) => { console.error(e); process.exit(1); });
