import { NextResponse } from "next/server";
import { isIndexableDeployment } from "@/lib/site";
import type { NextRequest } from "next/server";

import goneJson from "../docs/redirects/gone.json";
import redirectsJson from "../docs/redirects/redirects.json";

/**
 * Legacy URL edge layer (CLNT-175).
 *
 * `next.config.ts` already returns `docs/redirects/redirects.json` from
 * `redirects()`, which handles slash-free legacy paths. Two things it cannot do,
 * and this proxy does:
 *
 * 1. **410 Gone.** `docs/redirects/gone.json` lists 48 retired paths. `redirects()`
 *    can only redirect, so without this they would fall through to the 404 page —
 *    right for humans, wrong for crawlers.
 * 2. **Trailing slashes in a single hop.** Every legacy WordPress URL ends in `/`.
 *    Next.js normalizes the slash away with its own 308 *before* `redirects()` and
 *    *before* this proxy run (verified against a running server), so a legacy
 *    `/path/` costs one extra hop. Setting `skipTrailingSlashRedirect: true` in
 *    `next.config.ts` hands that normalization to this file, which then resolves
 *    `/path/` straight to its final destination (or 410) in one hop and falls back
 *    to Next's own behaviour — a 308 to the slash-free form — for everything else.
 *
 * The flag is the only piece missing; this file is written to be correct with or
 * without it. Without it the branches that see a trailing slash are simply never
 * reached and legacy `/path/` keeps costing the extra normalization hop.
 *
 * Both JSON files are generated by `scripts/redirects/build_redirect_map.py`.
 * Never edit them by hand; rerun the builder.
 */

type RedirectRule = { source: string; destination: string; permanent: boolean };

const GONE: ReadonlySet<string> = new Set(goneJson as string[]);

const REDIRECTS: ReadonlyMap<string, RedirectRule> = new Map(
  (redirectsJson as RedirectRule[]).map((rule) => [rule.source, rule]),
);

/** Collapse repeated slashes and drop the trailing slash, keeping the root as "/". */
function normalizePath(pathname: string): string {
  const collapsed = pathname.replace(/\/{2,}/g, "/");
  const stripped = collapsed.replace(/\/+$/, "");
  return stripped === "" ? "/" : stripped;
}

/**
 * The map is keyed on percent-decoded, lowercased paths (see the README's
 * "Normalization" section). Try the literal path first so nothing is matched more
 * loosely than `redirects()` would, then the decoded/lowercased form.
 */
function lookupKeys(pathname: string): string[] {
  const keys = [pathname];
  let decoded = pathname;
  try {
    decoded = decodeURIComponent(pathname);
  } catch {
    // Malformed percent-encoding: keep the raw path.
  }
  const lowered = decoded.toLowerCase();
  if (!keys.includes(lowered)) keys.push(lowered);
  return keys;
}

/** A small, crawler-friendly body for a permanently retired URL. */
function goneResponse(): NextResponse {
  const body = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Page removed &middot; ProSporter</title>
</head>
<body style="margin:0;padding:4rem 1.5rem;font:16px/1.6 system-ui,sans-serif;text-align:center">
<h1 style="font-size:1.5rem;margin:0 0 .5rem">This page has been removed</h1>
<p style="margin:0 0 1.5rem;color:#555">It was retired when ProSporter moved to its new store and there is no replacement.</p>
<p style="margin:0"><a href="/shop" style="color:#111">Shop all</a> &nbsp;&middot;&nbsp; <a href="/" style="color:#111">Home</a></p>
</body>
</html>
`;
  return new NextResponse(body, {
    status: 410,
    headers: {
      "content-type": "text/html; charset=utf-8",
      // Long enough to spare the origin a crawl storm, short enough that wiring a
      // real page later is not stuck behind a CDN cache. Never "immutable".
      "cache-control": "public, max-age=3600, must-revalidate",
      "x-robots-tag": "noindex",
    },
  });
}

export function proxy(request: NextRequest): NextResponse {
  const { pathname, search } = request.nextUrl;
  const normalized = normalizePath(pathname);

  for (const key of lookupKeys(normalized)) {
    if (GONE.has(key)) {
      return goneResponse();
    }
    const rule = REDIRECTS.get(key);
    if (rule) {
      return NextResponse.redirect(
        new URL(rule.destination + search, request.url),
        rule.permanent ? 308 : 307,
      );
    }
  }

  // Not a legacy URL. Reproduce Next's own trailing-slash normalization, which is
  // only skipped when `skipTrailingSlashRedirect: true` is set; without the flag
  // this never fires because Next has already normalized the path.
  if (normalized !== pathname) {
    return NextResponse.redirect(new URL(normalized + search, request.url), 308);
  }

  const response = NextResponse.next();
  // Before cutover the production alias duplicates the live WooCommerce store,
  // and previews duplicate production. robots.txt only stops crawling; this
  // header stops indexing of anything a crawler reaches through a link.
  if (!isIndexableDeployment()) {
    response.headers.set("x-robots-tag", "noindex, nofollow");
  }
  return response;
}

export const config = {
  // Skip framework internals, API routes and anything that looks like a file.
  // No legacy path in the map contains a dot, so nothing is lost.
  matcher: ["/((?!_next/static|_next/image|api/|.*\\.[^/]+$).*)"],
};
